qip:
  local-truststore:
    store:
      path: /app/truststore/defaulttruststore.jks
    certs:
      location: /app/cert/defaultsslcertificate

quarkus:
  log:
    level: ${ROOT_LOG_LEVEL:WARN}
    category:
      "org.qubership.integration.platform.engine":
        level: DEBUG
