quarkus:
  dbaas:
    api:
      agent:
        url: ${DBAAS_AGENT_URL:http://dbaas-agent:8080}
    datasources:
      checkpoints:
        jdbc:
          min-size: ${PG_MIN_IDLE:0}
          max-size: ${PG_MAX_POOL_SIZE:30}
      configs:
        jdbc:
          min-size: ${PG_MIN_IDLE:0}
          max-size: ${PG_MAX_POOL_SIZE:30}
    flyway:
      datasources:
        checkpoints:
          location: db/migration/postgresql/static
          baseline-on-migrate: true
          validate-on-migrate: true
          create-schemas: true
          out-of-order: true
          ignore-migration-patterns: '*:future,*:missing'
        configs:
          location: db/migration/postgresql/configs
          baseline-on-migrate: true
          validate-on-migrate: true
          create-schemas: true
          out-of-order: true
          ignore-migration-patterns: '*:future,*:missing'
